In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('shoporders.csv',
                 sep=',',
                 encoding='utf-8',
                 decimal=',',
                 parse_dates=['order_date']
                 )

df

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,payment_method
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,Kreditkarte
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,Twint
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,PayPal
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,Twint
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.1,CHF,2024-04-02,Switzerlaand,Rechnung
...,...,...,...,...,...,...,...,...,...,...,...
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,Twint
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,Rechnung
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.8,CHF,2024-03-06,Deutschland,Twint
210,1030,Monika Lehmann,Smartphone,Elektro,3,Stück,807.51,EUR,2024-04-17,Italien,Rechnung
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,Rechnung

In [ ]:


df['shipping_country'].value_counts(dropna=False)

In [ ]:
# Normalisiere shipping_country auf genau diese Zielwerte:
# Schweiz, Italien, Frankreich, Deutschland, Österreich

country_map = {
    # Schweiz
    "schweiz": "Schweiz",
    "switzerlaand": "Schweiz",
    "switerland": "Schweiz",
    "switzerland": "Schweiz",
    "ch": "Schweiz",

    # Italien
    "italien": "Italien",
    "italy": "Italien",

    # Deutschland
    "deutschland": "Deutschland",
    "deuschland": "Deutschland",
    "germany": "Deutschland",

    # Frankreich
    "frankreich": "Frankreich",
    "france": "Frankreich",

    # Österreich
    "österreich": "Österreich",
    "osterreich": "Österreich",
    "oestereich": "Österreich",
    "ostereich": "Österreich",
    "austria": "Österreich",
}

df["shipping_country"] = (
    df["shipping_country"]
    .astype("string")
    .str.strip() 
    .str.lower()
    .map(country_map)
)

df

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,payment_method
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,Kreditkarte
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,Twint
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,PayPal
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,Twint
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.1,CHF,2024-04-02,Schweiz,Rechnung
...,...,...,...,...,...,...,...,...,...,...,...
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,Twint
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,Rechnung
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.8,CHF,2024-03-06,Deutschland,Twint
210,1030,Monika Lehmann,Smartphone,Elektro,3,Stück,807.51,EUR,2024-04-17,Italien,Rechnung
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,Rechnung

In [ ]:
# Doppelte Zeilen entfernen und das DataFrame aktualisieren
df = df.drop_duplicates()
df

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,payment_method
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,Kreditkarte
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,Twint
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,PayPal
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,Twint
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.1,CHF,2024-04-02,Schweiz,Rechnung
...,...,...,...,...,...,...,...,...,...,...,...
206,1132,Andrea Wyss,Drucker,Büro,3,Stück,246.61,CHF,2024-02-09,Schweiz,Kreditkarte
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,Twint
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,Rechnung
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.8,CHF,2024-03-06,Deutschland,Twint
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,Rechnung

In [ ]:
# Wechselkurse (Beispielwerte; anpassen, falls du andere Kurse brauchst)
fx_rate = {
    "CHF": 1.0,
    "EUR": 0.96,   # 1 EUR = 0.96 CHF
    "USD": 0.88,   # 1 USD = 0.88 CHF
}
df['price'] = df['price'].fillna(0)

# Normalisiere Währungen
df["currency"] = df["currency"].astype("string").str.upper().str.strip()

# Preis in CHF umrechnen
df["price_chf"] = (
    df["price"]
    .astype(float)
    * df["currency"].map(fx_rate).fillna(1.0)
).round(2)

df

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,payment_method,price_chf,preis_total
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,Kreditkarte,9.41,9.41
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,Twint,813.87,813.87
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,PayPal,16.23,64.92
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,Twint,21.09,84.36
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.1,CHF,2024-04-02,Schweiz,Rechnung,120.10,600.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,1132,Andrea Wyss,Drucker,Büro,3,Stück,246.61,CHF,2024-02-09,Schweiz,Kreditkarte,246.61,739.83
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,Twint,408.63,2043.15
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,Rechnung,18.55,92.75
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.8,CHF,2024-03-06,Deutschland,Twint,272.80,272.8
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,Rechnung,94.03,282.09

In [ ]:
# Gesamtpreis berechnen; ein Dutzend entspricht 12 Stück
einheiten_pro_position = (
    df["unit"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map({
        "stück": 1,
        "stueck": 1,
        "stück": 1,
        "dutzend": 12,
        "dozen": 12,
    })
    .fillna(1)
)

df['price'] = df['price'].fillna(0)

df["preis_total"] = (
    df["price_chf"].astype("Float64")
    * df["quantity"].astype("Float64")
    * einheiten_pro_position
).round(2)

df

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,payment_method,price_chf,preis_total
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,Kreditkarte,9.41,9.41
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,Twint,813.87,813.87
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,PayPal,16.23,64.92
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,Twint,21.09,84.36
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.1,CHF,2024-04-02,Schweiz,Rechnung,120.10,600.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,1132,Andrea Wyss,Drucker,Büro,3,Stück,246.61,CHF,2024-02-09,Schweiz,Kreditkarte,246.61,739.83
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,Twint,408.63,2043.15
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,Rechnung,18.55,92.75
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.8,CHF,2024-03-06,Deutschland,Twint,272.80,272.8
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,Rechnung,94.03,282.09

Kurstag 5

In [ ]:
df_ohe = pd.get_dummies(df, columns=["payment_method"], prefix="pay")

df_ohe

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,price_chf,preis_total,pay_Kreditkarte,pay_PayPal,pay_Rechnung,pay_Twint
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,9.41,9.41,True,False,False,False
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,813.87,813.87,False,False,False,True
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,16.23,64.92,False,True,False,False
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,21.09,84.36,False,False,False,True
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.1,CHF,2024-04-02,Schweiz,120.10,600.5,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,1132,Andrea Wyss,Drucker,Büro,3,Stück,246.61,CHF,2024-02-09,Schweiz,246.61,739.83,True,False,False,False
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,408.63,2043.15,False,False,False,True
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,18.55,92.75,False,False,True,False
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.8,CHF,2024-03-06,Deutschland,272.80,272.8,False,False,False,True
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,94.03,282.09,False,False,True,False

In [ ]:
df_ohe["weekday"] = df_ohe['order_date'].dt.dayofweek

df_ohe["month"] = df_ohe['order_date'].dt.month

df_ohe["is_weekend"] = df_ohe['weekday'] >=5

df_ohe

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,price_chf,preis_total,pay_Kreditkarte,pay_PayPal,pay_Rechnung,pay_Twint,weekday,month,is_weekend
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,9.41,9.41,True,False,False,False,3,7,False
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,813.87,813.87,False,False,False,True,4,8,False
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,16.23,64.92,False,True,False,False,4,7,False
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,21.09,84.36,False,False,False,True,0,4,False
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.1,CHF,2024-04-02,Schweiz,120.10,600.5,False,False,True,False,1,4,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,1132,Andrea Wyss,Drucker,Büro,3,Stück,246.61,CHF,2024-02-09,Schweiz,246.61,739.83,True,False,False,False,4,2,False
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,408.63,2043.15,False,False,False,True,6,3,True
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,18.55,92.75,False,False,True,False,5,1,True
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.8,CHF,2024-03-06,Deutschland,272.80,272.8,False,False,False,True,2,3,False
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,94.03,282.09,False,False,True,False,4,12,False

In [ ]:
from sklearn.preprocessing import(
    StandardScaler,
    MinMaxScaler
)

scaler = StandardScaler()
df_ohe["price_scaled"] = scaler.fit_transform(df_ohe[["price_chf"]])

df_ohe

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,price_chf,preis_total,pay_Kreditkarte,pay_PayPal,pay_Rechnung,pay_Twint,weekday,month,is_weekend,price_scaled
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,9.41,9.41,True,False,False,False,3,7,False,-0.556246
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,813.87,813.87,False,False,False,True,4,8,False,2.812333
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,16.23,64.92,False,True,False,False,4,7,False,-0.527688
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,21.09,84.36,False,False,False,True,0,4,False,-0.507337
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.1,CHF,2024-04-02,Schweiz,120.10,600.5,False,False,True,False,1,4,False,-0.092745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,1132,Andrea Wyss,Drucker,Büro,3,Stück,246.61,CHF,2024-02-09,Schweiz,246.61,739.83,True,False,False,False,4,2,False,0.437000
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,408.63,2043.15,False,False,False,True,6,3,True,1.115439
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,18.55,92.75,False,False,True,False,5,1,True,-0.517973
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.8,CHF,2024-03-06,Deutschland,272.80,272.8,False,False,False,True,2,3,False,0.546668
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,94.03,282.09,False,False,True,False,4,12,False,-0.201910

In [ ]:
df_ohe.describe()

,order_id,quantity,order_date,price_chf,preis_total,weekday,month,price_scaled
count,200.000000,200.000000,200,200.000000,200.0,200.000000,200.000000,2.000000e+02
mean,1100.500000,3.040000,2024-06-23 15:43:12,142.248700,600.3317,3.085000,6.295000,-4.440892e-17
min,1001.000000,1.000000,2024-01-01 00:00:00,0.000000,0.0,0.000000,1.000000,-5.956492e-01
25%,1050.750000,2.000000,2024-04-02 00:00:00,18.767500,58.59,1.000000,4.000000,-5.170625e-01
50%,1100.500000,3.000000,2024-06-11 00:00:00,51.015000,197.125,3.000000,6.000000,-3.820300e-01
75%,1150.250000,4.000000,2024-09-12 06:00:00,117.775000,478.1175,5.000000,9.000000,-1.024806e-01
max,1200.000000,5.000000,2024-12-25 00:00:00,946.410000,8912.16,6.000000,12.000000,3.367328e+00
std,57.879185,1.351865,NaN,239.412171,1140.372512,1.951105,3.223341,1.002509e+00

In [ ]:
bins = [0, 25, 50, 75, 100, 125, 150, 200, 500, 1000]
labels = ["0-25", "25-50", "50-75", "75-100", "100-125", "125-150", "150-200", "200-500", "500-1000"]
df_ohe["price_group"] = pd.cut(df_ohe["price_chf"], bins=bins, labels=labels)

print("Begründung: Kleinere Schritte zuerst bis 75% der Daten abgedeckt sind.")

df_ohe

Begründung: Kleinere Schritte zuerst bis 75% der Daten abgedeckt sind.

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,...,preis_total,pay_Kreditkarte,pay_PayPal,pay_Rechnung,pay_Twint,weekday,month,is_weekend,price_scaled,price_group
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,...,9.41,True,False,False,False,3,7,False,-0.556246,0-25
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,...,813.87,False,False,False,True,4,8,False,2.812333,500-1000
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,...,64.92,False,True,False,False,4,7,False,-0.527688,0-25
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,...,84.36,False,False,False,True,0,4,False,-0.507337,0-25
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.1,CHF,2024-04-02,Schweiz,...,600.5,False,False,True,False,1,4,False,-0.092745,100-125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,1132,Andrea Wyss,Drucker,Büro,3,Stück,246.61,CHF,2024-02-09,Schweiz,...,739.83,True,False,False,False,4,2,False,0.437000,200-500
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,...,2043.15,False,False,False,True,6,3,True,1.115439,200-500
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,...,92.75,False,False,True,False,5,1,True,-0.517973,0-25
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.8,CHF,2024-03-06,Deutschland,...,272.8,False,False,False,True,2,3,False,0.546668,200-500
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,...,282.09,False,False,True,False,4,12,False,-0.201910,75-100

In [ ]:
df1 = df_ohe[['customer_name'],['order_id'],['preis_total']]
df1

In [ ]:

df1["customer_avg_order"] = (df1.groupby('customer_name')['preis_total'].transform('mean'))

df1